// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TodoDemoApp.Models;

namespace TodoDemoApp.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoDemoApp.Models.Person", b =>
                {
                    b.Property<long>("PId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TodoDemoApp.Models.TodoItem", b =>
                {
                    b.Property<long>("Id");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("PId");

                    b.HasKey("Id");

                    b.HasIndex("PId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoDemoApp.Models.TodoItem", b =>
                {
                    b.HasOne("TodoDemoApp.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
